### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Kalemis** [cmda-bt/pt-course-18-19#45] opened 2019-03-16 11:35 UTC
# Config

## Name
Artemis

## Class
Bt-1

## GitHub username
Kalemis

## GitHub repository
[Repository](https://github.com/Kalemis/project-tech)

## Add a screenshot of your editor
I never really liked to add custom colors to my editor. In VScode I really like the readability, I can read everything at daytime and at nighttime. So that's no reason for me to add custom colors. I also work a lot in regular Visual Studio for windows where I use the same default color scheme. 

## Summary
This weak I made some progress in creating my feature. The code I made for the assignments are already applicable to my feature. I also defined my feature a lot more and it is more clear to me what I am actually going to make. This week I also did 3 pull requests on my classmates repositories. I created a seperate issue for that, but now I'm doubting if that was what I was supposed to do... Sorry!

**Comment by dandevri** [comment] 2019-03-18 17:25
Duplicate of #41

**Closed as completed by dandevri** 2019-03-18 17:25 UTC
Labels: tech-2, week-4, week-4-config
